/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

typedef struct LKTransform {
    float m11;
    float m12;
    float m13;
    float m14;
    float m21;
    float m22;
    float m23;
    float m24;
    float m31;
    float m32;
    float m33;
    float m34;
    float m41;
    float m42;
    float m43;
    float m44;
} LKTransform;

extern LKTransform LKTransformIdentity;

LKTransform LKTransformRotate(LKTransform transform, float radians, float x, float y, float z);
LKTransform LKTransformMakeRotation(float radians, float x, float y, float z);