/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIView.h>
#import "UIButtonBar.h"
#import "UIKeyboard.h"
#import "UIPushButton.h"
#import "UITable.h"
#import "UITextLabel.h"
#import <UIKit/UIWindow.h>
#import <UIKit/UIActionSheet.h>

#define UIAlertSheet UIActionSheet