/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSArray;

@interface UIButtonBar : UIView
{
    struct __CFDictionary *_groups;
    NSArray *_buttonItems;
    int _currentButtonGroup;
    struct __CFArray *_hiddenItems;
    int _selectedTag;
    int _trackingTag;
    UIView *_customizeView;
    id _delegate;
    struct {
        unsigned int barStyle:3;
        unsigned int roundsCorners:1;
        unsigned int alertShown:1;
        unsigned int wasEnabled:1;
        unsigned int trackingMode:2;
        unsigned int customized:1;
        unsigned int downButtonSentAction:1;
        unsigned int reserved:22;
    } _buttonBarFlags;
}

+ (Class)defaultButtonClass;    // IMP=0x32421228
+ (struct __GSFont *)defaultButtonFont; // IMP=0x32421278
+ (float)defaultHeight; // IMP=0x3242128c
+ (float)defaultHeightForBarSize:(int)fp8;      // IMP=0x324212cc
+ (float)defaultSelectionModeHeight;    // IMP=0x324212ac
+ (Class)defaultTextButtonClass;        // IMP=0x32421250
- (void)_buttonBarFinishedAnimating;    // IMP=0x3242175c
- (void)_customizeDone:(id)fp8; // IMP=0x32421c54
- (void)_dismissCustomizeSheet:(BOOL)fp8;       // IMP=0x32425a94
- (void)_finishCustomizeAnimation:(id)fp8;      // IMP=0x32421b78
- (void)animateWithDuration:(float)fp8 forButton:(int)fp12;     // IMP=0x32422090
- (int)barStyle;        // IMP=0x32421750
- (id)createButtonWithDescription:(id)fp8;      // IMP=0x32424734
- (int)currentButtonGroup;      // IMP=0x32421954
- (void)customize:(const int *)fp8 withCount:(int)fp12; // IMP=0x32428ebc
- (void)dealloc;        // IMP=0x32421668
- (void)dismissCustomizeSheet:(BOOL)fp8;        // IMP=0x32421c74
- (void)drawRect:(struct CGRect)fp8;    // IMP=0x32425730
- (void)getVisibleButtonTags:(int *)fp8 count:(unsigned int *)fp12 maxItems:(unsigned int)fp16; // IMP=0x3242195c
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;    // IMP=0x32421ca4
- (id)initInView:(id)fp8 withFrame:(struct CGRect)fp12 withItemList:(id)fp28;   // IMP=0x324213dc
- (id)initInView:(id)fp8 withItemList:(id)fp12; // IMP=0x32425c7c
- (void)mouseDown:(struct __GSEvent *)fp8;      // IMP=0x32421d28
- (void)mouseDragged:(struct __GSEvent *)fp8;   // IMP=0x32421d8c
- (void)mouseUp:(struct __GSEvent *)fp8;        // IMP=0x32421df0
- (BOOL)onStateForButton:(int)fp8;      // IMP=0x32422028
- (void)positionButtons:(id)fp8 tags:(int *)fp12 count:(int)fp16 group:(int)fp20;       // IMP=0x32429394
- (void)registerButtonGroup:(int)fp8 withButtons:(int *)fp12 withCount:(int)fp16;       // IMP=0x324217fc
- (int)selectedButton;  // IMP=0x32421e54
- (void)setBadgeGlyph:(id)fp8 forButton:(int)fp12;      // IMP=0x32421fb8
- (void)setBadgeValue:(id)fp8 forButton:(int)fp12;      // IMP=0x32421f4c
- (void)setBarStyle:(int)fp8;   // IMP=0x324216f0
- (void)setButtonBarTrackingMode:(int)fp8;      // IMP=0x32424614
- (void)setDelegate:(id)fp8;    // IMP=0x32421a50
- (void)setFrame:(struct CGRect)fp8;    // IMP=0x32425f54
- (void)setOnStateForButton:(BOOL)fp8 forButton:(int)fp12;      // IMP=0x32422058
- (void)showButtonGroup:(int)fp8 withDuration:(double)fp12;     // IMP=0x324218c8
- (void)showButtons:(int *)fp8 withCount:(int)fp12 withDuration:(double)fp16;   // IMP=0x3242178c
- (void)showSelectionForButton:(int)fp8;        // IMP=0x32421e5c

@end