/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "UITableCell.h"

@class UIImageView, UITextLabel;

@interface UIImageAndTextTableCell : UITableCell
{
    UITextLabel *_titleTextLabel;
    UIImageView *_iconImageView;
}

+ (struct __GSFont *)defaultTitleFont;	// IMP=0x323eb050
- (struct CGColor *)_getTitleColor;	// IMP=0x323eb2b8
- (int)alignment;	// IMP=0x323eb498
- (void)dealloc;	// IMP=0x323eafe8
- (id)iconImageView;	// IMP=0x323eb3e4
- (struct CGPoint)iconInset;	// IMP=0x323ecee8
- (id)image;	// IMP=0x323eb298
- (void)layoutSubviews;	// IMP=0x323ebb24
- (void)setAlignment:(int)fp8;	// IMP=0x323eb480
- (void)setEnabled:(BOOL)fp8;	// IMP=0x323eb330
- (void)setImage:(id)fp8;	// IMP=0x323eb9e4
- (void)setTitle:(id)fp8;	// IMP=0x323eb22c
- (struct CGPoint)textInset;	// IMP=0x323ecefc
- (id)title;	// IMP=0x323eb278
- (id)titleTextLabel;	// IMP=0x323eb064
- (void)updateHighlightColors;	// IMP=0x323eb2cc

@end

