/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "UIPreferencesTableCell.h"

@class UITextField, UITextLabel;

@interface UIPreferencesTextTableCell : UIPreferencesTableCell
{
    UITextField *_textField;
    UITextLabel *_valueSuffixLabel;
    float _textFieldOffset;
    SEL _returnAction;
}

- (struct CGColor *)_disabledFontColor;	// IMP=0x3244dbc4
- (void)_textFieldEndEditing:(id)fp8;	// IMP=0x3244e26c
- (void)_textFieldEndEditingOnReturn:(id)fp8;	// IMP=0x3244e3ec
- (void)_textFieldStartEditing:(id)fp8;	// IMP=0x3244e1fc
- (void)_textValueChanged:(id)fp8;	// IMP=0x3244e498
- (void)_updateSuffixFrame;	// IMP=0x3244e87c
- (unsigned int)becomeFirstResponder;	// IMP=0x3244dbfc
- (BOOL)canBecomeFirstResponder;	// IMP=0x3244dc1c
- (void)dealloc;	// IMP=0x3244daf4
- (BOOL)hasValueSuffix;	// IMP=0x3244df58
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3244d758
- (id)keyboardInputOverlayContainer:(id)fp8;	// IMP=0x3244da90
- (void)layoutSubviews;	// IMP=0x3244e5e4
- (void)resignFirstResponder;	// IMP=0x3244dc40
- (void)setEnabled:(BOOL)fp8;	// IMP=0x3244dc60
- (void)setPlaceHolderValue:(id)fp8;	// IMP=0x3244e5c4
- (void)setReturnAction:(SEL)fp8;	// IMP=0x3244daec
- (void)setTextFieldOffset:(float)fp8;	// IMP=0x3244daac
- (void)setValue:(id)fp8;	// IMP=0x3244df68
- (void)setValueSuffix:(id)fp8;	// IMP=0x3244dd4c
- (id)textField;	// IMP=0x3244e5bc
- (void)textFieldDidBecomeFirstResponder:(id)fp8;	// IMP=0x3244e058
- (float)textFieldOffset;	// IMP=0x3244dae4
- (id)value;	// IMP=0x3244e0e8
- (id)valueTextLabel;	// IMP=0x3244e1a0

@end

