/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "UIImageAndTextTableCell.h"

@class UIBezierPath, UIImageView, UITextLabel;

@interface UIPreferencesTableCell : UIImageAndTextTableCell
{
    int _cellOutline;
    id _value;
    SEL _action;
    id _target;
    UIImageView *_checkedImageView;
    UIBezierPath *_fillPath;
    UIBezierPath *_strokePath;
    UITextLabel *_valueTextLabel;
    unsigned int _radioGroupItem:1;
    unsigned int _ignoreRemoveFromSuperView:1;
    unsigned int _drawAsLabel:1;
    unsigned int _drawAsGroupTitle:1;
    unsigned int _drawsBackground:1;
    unsigned int _blueDisclosureCircle:1;
    unsigned int _checkStyle:4;
    unsigned int _superViewIsPrefTable:1;
    unsigned int _dontHighlightOnMouseDown:1;
    unsigned int _tracking:1;
    unsigned int _valueChanged:1;
    unsigned int _removeControlVisible:1;
    unsigned int _dontIndentForRemoveControl:1;
    unsigned int _reserved:16;
}

+ (struct __GSFont *)defaultTitleFont;	// IMP=0x32444cb0
+ (Class)valueTextLabelClass;	// IMP=0x32446038
- (void)_animateRemoveControlVisible:(BOOL)fp8;	// IMP=0x32447280
- (struct CGImage *)_cachedBackgroundImage;	// IMP=0x3244576c
- (float)_cellInset;	// IMP=0x32444b88
- (id)_checkMarkImage;	// IMP=0x32446438
- (id)_copyBackgroundButtonViewWithFrame:(struct CGRect)fp8;	// IMP=0x32445a60
- (void)_createBezierPathWithCornerRadius:(float)fp8 bottomRadius:(float)fp12 animating:(BOOL)fp16;	// IMP=0x32448a7c
- (struct CGImage *)_createCachedPrefImage;	// IMP=0x32445710
- (struct CGContext *)_createContextForCaching;	// IMP=0x3244869c
- (struct CGColor *)_getTitleColor;	// IMP=0x32446004
- (void)_invalidatePaths;	// IMP=0x3244544c
- (void)_layoutDisclosureIfNeeded;	// IMP=0x32448214
- (void)_layoutSubviewsAnimated:(BOOL)fp8;	// IMP=0x32445898
- (void)_removeContextFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x32445990
- (void)_removeContextFromSuperviewAndRedislaySelf:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x324459b0
- (void)_setDrawAsGroupTitle:(BOOL)fp8;	// IMP=0x32446748
- (void)_setDrawAsLabel:(BOOL)fp8;	// IMP=0x32448d70
- (void)_setHighlightOnMouseDown:(BOOL)fp8;	// IMP=0x32444e4c
- (void)_setIgnoreRemoveFromSuperView:(BOOL)fp8;	// IMP=0x32446cdc
- (void)_setRadioGroupItem:(BOOL)fp8;	// IMP=0x324464b4
- (void)_setSuperviewsIsPrefTable:(BOOL)fp8;	// IMP=0x32444cc4
- (void)_unhighlight;	// IMP=0x32444fa4
- (void)_updateButtonSizeForRemoveControlVisible:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x32445bf0
- (SEL)action;	// IMP=0x32446430
- (struct CGRect)buttonBounds;	// IMP=0x32444bac
- (int)cellOutline;	// IMP=0x32445988
- (struct CGRect)contentBounds;	// IMP=0x32446fd8
- (id)createRemoveControl;	// IMP=0x324469ec
- (void)dealloc;	// IMP=0x32445374
- (id)disclosureImage;	// IMP=0x32446688
- (id)disclosurePressedImage;	// IMP=0x324466e8
- (float)disclosureRightMargin;	// IMP=0x324462f0
- (void)drawBackgroundInRect:(struct CGRect)fp8 withFade:(float)fp24;	// IMP=0x324455f4
- (id)enclosingPreferencesTable;	// IMP=0x32444c7c
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3244635c
- (BOOL)indentsBackgroundForRemoveControl;	// IMP=0x324469dc
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324452fc
- (BOOL)isChecked;	// IMP=0x32446678
- (void)layoutSubviews;	// IMP=0x32447b84
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x324451ec
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x32444e78
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x32444fc4
- (void)movedToSuperview:(id)fp8;	// IMP=0x32444cdc
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x32444d84
- (float)removeButtonAnimationDuration;	// IMP=0x32445bc4
- (void)removeControl:(id)fp8 willRemoveTarget:(id)fp12;	// IMP=0x32445d0c
- (void)removeControlWillHideRemoveButton:(id)fp8 animated:(BOOL)fp12;	// IMP=0x32445cb4
- (void)removeControlWillShowRemoveButton:(id)fp8 animated:(BOOL)fp12;	// IMP=0x32445c5c
- (void)removeFromSuperview;	// IMP=0x32445400
- (void)setAction:(SEL)fp8;	// IMP=0x32446428
- (void)setCellOutline:(int)fp8;	// IMP=0x324458fc
- (void)setCheckStyle:(int)fp8;	// IMP=0x324464dc
- (void)setChecked:(BOOL)fp8;	// IMP=0x32446544
- (void)setDrawsBackground:(BOOL)fp8;	// IMP=0x324454a4
- (void)setEnabled:(BOOL)fp8;	// IMP=0x32446d08
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x324454ec
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x32444e04
- (void)setIcon:(id)fp8;	// IMP=0x32446b20
- (void)setIndentsBackgroundForRemoveControl:(BOOL)fp8;	// IMP=0x324469bc
- (void)setNeedsDisplay;	// IMP=0x32445288
- (void)setSelected:(BOOL)fp8 withFade:(BOOL)fp12;	// IMP=0x32446c40
- (void)setTarget:(id)fp8;	// IMP=0x32446418
- (void)setUsesBlueDisclosureCircle:(BOOL)fp8;	// IMP=0x324483f4
- (void)setValue:(id)fp8;	// IMP=0x324461c8
- (void)sizeToFit;	// IMP=0x32446864
- (id)target;	// IMP=0x32446420
- (void)updateHighlightColors;	// IMP=0x32446b58
- (id)value;	// IMP=0x324462e8
- (struct CGColor *)valueColor;	// IMP=0x32445fbc
- (id)valueTextLabel;	// IMP=0x32446060

@end

