/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "UITable.h"

@class NSMutableArray, UIKeyboard, UIPreferencesTableCell;

@interface UIPreferencesTable : UITable
{
    UIPreferencesTableCell *_editingCell;
    int _editingCellRow;
    NSMutableArray *_groupItems;
    UIKeyboard *_keyboard;
    float _textOffset;
    struct __CFDictionary *_piecesForCell;
    unsigned int _datasourceCellForGroup:1;
    unsigned int _datasourceIsRadioGroup:1;
    unsigned int _datasourceIsLabelGroup:1;
    unsigned int _datasourceIsRowCheckedInRadioGroup:1;
    unsigned int _centersContent:1;
    unsigned int _reserved:27;
}

- (void)_animatePiecesOfCell:(id)fp8 isFirstItemInGroup:(BOOL)fp12 isDeletion:(BOOL)fp16 isDestinationRowFrame:(struct CGRect)fp20;	// IMP=0x324444ec
- (BOOL)_beginEditingNextCell;	// IMP=0x324419a4
- (int)_cellOutlineForRow:(int)fp8 withChildCount:(int)fp12 isLabelGroup:(BOOL)fp16;	// IMP=0x3243f760
- (id)_copyPieceOfCell:(id)fp8 withContentsPosition:(int)fp12;	// IMP=0x32440974
- (id)_editingCell;	// IMP=0x3244184c
- (id)_existingPieceForCell:(id)fp8;	// IMP=0x32440904
- (void)_fadeCellOutAnimationDidStop:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x32440b5c
- (void)_fadeCellOutAnimationDidStopAndFixOutlines:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x32440ce4
- (void)_fadeCellSelection;	// IMP=0x3243f068
- (id)_groupItemForTableRow:(int)fp8 andGroupIndex:(int *)fp12 andRow:(int *)fp16;	// IMP=0x3243f204
- (id)_groupItemForTableRow:(int)fp8 andGroupIndex:(int *)fp12 andRow:(int *)fp16 inGroups:(id)fp20;	// IMP=0x3243f0f0
- (void)_keyboardRemoveAnimationCompleted:(id)fp8;	// IMP=0x32441288
- (int)_paddingForCenteringContent;	// IMP=0x3244023c
- (void)_removeContextFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x32440c00
- (void)_removePiecesFromSuperview:(id)fp8;	// IMP=0x32440c20
- (void)_removePiecesFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;	// IMP=0x32440cc4
- (void)_setAlpha:(float)fp8 forSubviewsOf:(id)fp12;	// IMP=0x32440874
- (void)_setEditingCell:(id)fp8;	// IMP=0x32441854
- (void)_updateContentSize;	// IMP=0x324404a0
- (void)_updatePaddingForCenteringContent;	// IMP=0x324403e8
- (BOOL)_userCanDeleteRows;	// IMP=0x324411e8
- (id)_visibleCheckedCellInTableRowRange:(struct _NSRange)fp8;	// IMP=0x32442068
- (void)addTableColumn:(id)fp8;	// IMP=0x3243efa0
- (void)animateDeletionOfRowWithCell:(id)fp8 viaEdge:(int)fp12;	// IMP=0x32440554
- (float)animationDuration;	// IMP=0x32440aac
- (BOOL)canDeleteRow:(int)fp8;	// IMP=0x3243ee70
- (BOOL)canHandleSwipes;	// IMP=0x3243ee68
- (BOOL)canInsertAtRow:(int)fp8;	// IMP=0x3243ef08
- (BOOL)canSelectRow:(int)fp8;	// IMP=0x3243f01c
- (id)dataSourceCreateCellForRow:(int)fp8 column:(int)fp12 reusing:(id)fp16;	// IMP=0x3243f7b0
- (int)dataSourceGetRowCount;	// IMP=0x3243f4e0
- (BOOL)dataSourceSupportsVariableRowHeights;	// IMP=0x3244050c
- (void)dealloc;	// IMP=0x3243ec50
- (void)deleteItems:(id)fp8;	// IMP=0x32440b2c
- (void)deleteRows:(id)fp8 viaEdge:(int)fp12;	// IMP=0x32440840
- (int)editingRow;	// IMP=0x3244199c
- (void)enableRowDeletion:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x32440f2c
- (BOOL)floatArray:(id)fp8 loadValues:(float *)fp12 count:(int)fp16;	// IMP=0x3243fec4
- (struct CGRect)frameOfPreferencesCellAtRow:(int)fp8 inGroup:(int)fp12;	// IMP=0x3243fe50
- (BOOL)getGroup:(int *)fp8 row:(int *)fp12 forTableRow:(int)fp16;	// IMP=0x3243f30c
- (BOOL)getGroup:(int *)fp8 row:(int *)fp12 ofPreferencesTableCell:(id)fp16;	// IMP=0x3243f260
- (int)groupForTableRow:(int)fp8;	// IMP=0x3243f2d8
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3243ecb8
- (void)insertItems:(id)fp8;	// IMP=0x32440b00
- (void)insertItems:(id)fp8 deleteItems:(id)fp12 andReloadIndexes:(id)fp16;	// IMP=0x324421c0
- (id)keyboard;	// IMP=0x32441280
- (BOOL)keyboardVisible;	// IMP=0x32441270
- (void)reloadData;	// IMP=0x32440ab8
- (void)scrollAndCenterTableCell:(id)fp8 animated:(BOOL)fp12;	// IMP=0x32441344
- (void)selectRow:(int)fp8 byExtendingSelection:(BOOL)fp12 withFade:(BOOL)fp16;	// IMP=0x32441d98
- (void)setBottomBufferHeight:(float)fp8;	// IMP=0x324412ec
- (void)setCentersContent:(BOOL)fp8;	// IMP=0x32440438
- (void)setDataSource:(id)fp8;	// IMP=0x3243f348
- (void)setKeyboardVisible:(BOOL)fp8;	// IMP=0x324412c8
- (void)setKeyboardVisible:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x324413a8
- (BOOL)shouldIndentRow:(int)fp8;	// IMP=0x32440734
- (int)tableRowForRow:(int)fp8 inGroup:(int)fp12;	// IMP=0x3243f09c
- (BOOL)validateDataSource;	// IMP=0x3243f47c
- (id)visiblePreferencesCellForRow:(int)fp8 inGroup:(int)fp12;	// IMP=0x32440514

@end

