/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "UISliderControl.h"

@class UIImage;

@interface UISwitchControl : UISliderControl
{
    struct __GSFont *_font;
    UIImage *_leftCapShadowed;
    UIImage *_rightCapShadowed;
    UIImage *_leftCapShadowedDown;
    UIImage *_rightCapShadowedDown;
}

- (void)_drawText:(id)fp8 inRect:(struct CGRect)fp12 selected:(BOOL)fp28;	// IMP=0x3244d274
- (struct __GSFont *)_font;	// IMP=0x3244c868
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x3244c95c
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x3244c894
- (id)createSliderKnobView;	// IMP=0x3244d66c
- (void)dealloc;	// IMP=0x3244c694
- (void)drawSliderInRect:(struct CGRect)fp8 dirtyRect:(struct CGRect)fp24;	// IMP=0x3244cdb0
- (void)drawSliderPiece:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x3244d0dc
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x3244ca3c
- (id)imageForSliderPiece:(int)fp8;	// IMP=0x3244c7bc
- (id)init;	// IMP=0x3244d6f0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3244c524
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x3244cbfc
- (void)setAlternateColors:(BOOL)fp8;	// IMP=0x3244cd68
- (void)setEnabled:(BOOL)fp8;	// IMP=0x3244c724
- (void)setLeftSwitchTitle:(id)fp8;	// IMP=0x3244c784
- (void)setRightSwitchTitle:(id)fp8;	// IMP=0x3244c7a0

@end

