/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface UITableColumn : NSObject
{
    NSString *_identifier;
    NSString *_title;
    float _width;
}

- (void)dealloc;	// IMP=0x323e85b8
- (id)identifier;	// IMP=0x323e86b8
- (id)initWithTitle:(id)fp8 identifier:(id)fp12 width:(float)fp16;	// IMP=0x323e8528
- (void)setIdentifier:(id)fp8;	// IMP=0x323e8670
- (void)setTitle:(id)fp8;	// IMP=0x323e8628
- (void)setWidth:(float)fp8;	// IMP=0x323e86c8
- (id)title;	// IMP=0x323e8620
- (float)width;	// IMP=0x323e86c0

@end

