/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class _UITableCellTransientData;

@interface UITableCell : UIView
{
    _UITableCellTransientData *_transientData;
    float _rightMargin;
    struct {
        unsigned int dontShowSelection:1;
        unsigned int showDisclosure:1;
        unsigned int showTopSeparator:1;
        unsigned int separatorStyle:3;
        unsigned int selectionStyle:2;
        unsigned int hideDisclosure:1;
        unsigned int isBeingDeleted:1;
        unsigned int disclosureClickable:1;
        unsigned int selectionFadeFraction:11;
        unsigned int disclosureStyle:1;
        unsigned int showingRemoveControl:1;
        unsigned int alignment:3;
        unsigned int showDisclosureWhenReordering:1;
        unsigned int fadeDisclosure:1;
        unsigned int reserved:3;
    } _tableCellFlags;
    UIView *_disclosureView;
}

- (id)_createDisclosureView;	// IMP=0x323ea32c
- (void)_deselectWithFlashCount:(int)fp8 duration:(double)fp12;	// IMP=0x323e8e40
- (id)_disclosureView;	// IMP=0x323e9ca8
- (void)_finishedFadingGrabber:(id)fp8 finished:(BOOL)fp12;	// IMP=0x323e9530
- (void)_grabberBeganReorder:(id)fp8;	// IMP=0x323e95a4
- (void)_grabberDragged:(id)fp8 yDelta:(float)fp12;	// IMP=0x323ec374
- (void)_grabberReleased:(id)fp8;	// IMP=0x323e95d8
- (id)_grabberView;	// IMP=0x323e92dc
- (BOOL)_isReordering;	// IMP=0x323e92b8
- (void)_layoutSubviewsAnimated:(BOOL)fp8;	// IMP=0x323e9cbc
- (void)_releaseGrabber;	// IMP=0x323e9468
- (void)_releaseRemoveControl;	// IMP=0x323e9818
- (void)_setDrawsTopSeparator:(BOOL)fp8;	// IMP=0x323ea3f8
- (void)_setGrabberHidden:(BOOL)fp8;	// IMP=0x323e9ad8
- (void)_setRemoveCharge:(float)fp8;	// IMP=0x323ea3c4
- (void)_setRightMargin:(float)fp8;	// IMP=0x323e9c88
- (void)_setSelectionFadeFraction:(float)fp8;	// IMP=0x323ec008
- (void)_setShowIndentSpacer:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x323e9d8c
- (BOOL)_shouldTryPromoteDescendantToFirstResponder;	// IMP=0x323ea464
- (void)_showDeleteOrInsertion:(BOOL)fp8 withDisclosure:(BOOL)fp12 animated:(BOOL)fp16 isDelete:(BOOL)fp20 andRemoveConfirmation:(BOOL)fp24;	// IMP=0x323e9ee8
- (void)_uiRemoveControlMinusButtonHideAnimationDone:(id)fp8;	// IMP=0x323ea1cc
- (void)_willBeDeleted;	// IMP=0x323ea20c
- (BOOL)cancelMouseTracking;	// IMP=0x323e9288
- (struct CGRect)contentBounds;	// IMP=0x323eb720
- (id)createInsertControl;	// IMP=0x323e9aa0
- (id)createRemoveControl;	// IMP=0x323e9a14
- (void)dealloc;	// IMP=0x323e8aa8
- (id)disclosureImage;	// IMP=0x323e8930
- (id)disclosurePressedImage;	// IMP=0x323e89ec
- (float)disclosureRightMargin;	// IMP=0x323e954c
- (void)drawBackgroundInRect:(struct CGRect)fp8 withFade:(float)fp24;	// IMP=0x323e971c
- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;	// IMP=0x323e9808
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323e930c
- (void)drawSeparatorInRect:(struct CGRect)fp8;	// IMP=0x323edb70
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x323e9144
- (void)insertControl:(id)fp8 shouldInsertWithTarget:(id)fp12;	// IMP=0x323ea2f8
- (BOOL)isAtLeastHalfSelected;	// IMP=0x323e8df8
- (BOOL)isRemoveControlVisible;	// IMP=0x323e9edc
- (BOOL)isReorderingEnabled;	// IMP=0x323e9558
- (BOOL)isSelected;	// IMP=0x323e8f5c
- (void)layoutSubviews;	// IMP=0x323ec120
- (float)removeButtonAnimationDuration;	// IMP=0x323e9cb0
- (id)removeControl;	// IMP=0x323e8bb0
- (void)removeControl:(id)fp8 didRemoveTarget:(id)fp12;	// IMP=0x323ea2c4
- (BOOL)removeControl:(id)fp8 shouldRemoveTarget:(id)fp12;	// IMP=0x323ea244
- (void)removeControl:(id)fp8 willRemoveTarget:(id)fp12;	// IMP=0x323ea27c
- (void)removeControlWillHideRemoveConfirmation:(id)fp8;	// IMP=0x323e9be4
- (void)removeControlWillShowRemoveConfirmation:(id)fp8;	// IMP=0x323e9ba4
- (void)removeFromSuperview;	// IMP=0x323e98c4
- (float)selectionPercent;	// IMP=0x323e8e18
- (int)separatorStyle;	// IMP=0x323e9098
- (void)setAlpha:(float)fp8;	// IMP=0x323e90c8
- (void)setDisclosureClickable:(BOOL)fp8;	// IMP=0x323e99b8
- (void)setDisclosureStyle:(int)fp8;	// IMP=0x323eb4a4
- (void)setEnableReordering:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x323ec508
- (void)setSelected:(BOOL)fp8;	// IMP=0x323e8f38
- (void)setSelected:(BOOL)fp8 withFade:(BOOL)fp12;	// IMP=0x323e8bc0
- (void)setSelectionStyle:(int)fp8;	// IMP=0x323e9048
- (void)setSeparatorStyle:(int)fp8;	// IMP=0x323e8fc0
- (void)setShowDisclosure:(BOOL)fp8;	// IMP=0x323e9024
- (void)setShowDisclosure:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x323ed218
- (void)setShowDisclosureWhenReordering:(BOOL)fp8;	// IMP=0x323e957c
- (void)setShowSelection:(BOOL)fp8;	// IMP=0x323e8f70
- (BOOL)showDisclosure;	// IMP=0x323e90b8
- (BOOL)showDisclosureWhenReordering;	// IMP=0x323e9594
- (BOOL)showSelection;	// IMP=0x323e90a8
- (void)updateHighlightColors;	// IMP=0x323e8df4

@end

