/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITransitionView : UIView
{
    UIView *_fromView;
    UIView *_toView;
    UIView *_firstResponderToRemember;
    id _delegate;
    struct {
        unsigned int animationInProgress:1;
        unsigned int ignoresInteractionEvents:1;
        unsigned int reserved:30;
    } _transitionViewFlags;
}

+ (double)defaultDurationForTransition:(int)fp8;	// IMP=0x323edd94
- (void)_didCompleteTransition:(BOOL)fp8;	// IMP=0x323ede98
- (void)_didStartTransition;	// IMP=0x323ede44
- (void)_markRememberedFirstResponderFromView:(id)fp8;	// IMP=0x323eddf4
- (void)_startTransition:(int)fp8 withDuration:(float)fp12;	// IMP=0x323ee2f8
- (void)_transitionDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x323ee2b8
- (void)dealloc;	// IMP=0x323edca0
- (id)delegate;	// IMP=0x323ee288
- (double)durationForTransition:(int)fp8;	// IMP=0x323edd08
- (id)fromView;	// IMP=0x323ee264
- (BOOL)ignoresInteractionEvents;	// IMP=0x323ee290
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323edbf4
- (BOOL)isTransitioning;	// IMP=0x323ee274
- (void)notifyDidCompleteTransition:(id)fp8;	// IMP=0x323ee0ec
- (void)setDelegate:(id)fp8;	// IMP=0x323ee280
- (void)setIgnoresInteractionEvents:(BOOL)fp8;	// IMP=0x323ee2a0
- (id)toView;	// IMP=0x323ee26c
- (BOOL)transition:(int)fp8 fromView:(id)fp12 toView:(id)fp16;	// IMP=0x323ee5fc
- (BOOL)transition:(int)fp8 toView:(id)fp12;	// IMP=0x323ee058

@end

