/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface AVSystemController : NSObject
{
    struct AVSystemControllerPrivate *_priv;
}

+ (id)sharedAVSystemController; // IMP=0x30299cf4
- (BOOL)activeCategoryVolumeDidChangeTo:(float)fp8 forRoute:(id)fp12 andDeviceIdentifier:(id)fp16;      // IMP=0x3029a3b0
- (id)attributeForKey:(id)fp8;  // IMP=0x3029a5ac
- (BOOL)changeActiveCategoryVolumeBy:(float)fp8;        // IMP=0x3029a1a8
- (BOOL)changeActiveCategoryVolumeBy:(float)fp8 fallbackCategory:(id)fp12 resultVolume:(float *)fp16 affectedCategory:(id *)fp20;       // IMP=0x3029a134
- (BOOL)changeActiveCategoryVolumeBy:(float)fp8 forRoute:(id)fp12 andDeviceIdentifier:(id)fp16; // IMP=0x3029a328
- (void)dealloc;        // IMP=0x30299fa4
- (BOOL)getActiveCategoryMuted:(char *)fp8;     // IMP=0x3029a4bc
- (BOOL)getActiveCategoryMuted:(char *)fp8 forRoute:(id)fp12 andDeviceIdentifier:(id)fp16;      // IMP=0x3029a514
- (BOOL)getActiveCategoryVolume:(float *)fp8 andName:(id *)fp12;        // IMP=0x3029a2f8
- (BOOL)getActiveCategoryVolume:(float *)fp8 andName:(id *)fp12 fallbackCategory:(id)fp16;      // IMP=0x3029a28c
- (BOOL)getActiveCategoryVolume:(float *)fp8 andName:(id *)fp12 forRoute:(id)fp16 andDeviceIdentifier:(id)fp20; // IMP=0x3029a3f4
- (id)init;     // IMP=0x30299d48
- (void)makeError:(id *)fp8 withDescription:(id)fp12 code:(long)fp16;   // IMP=0x3029aa80
- (BOOL)okToNotifyFromThisThread;       // IMP=0x3029ac0c
- (void)postServerConnectionDiedNotification:(id)fp8;   // IMP=0x3029ab48
- (void)postServerConnectionDiedNotificationAfterZeroDelay:(id)fp8;     // IMP=0x3029abcc
- (id)routeForCategory:(id)fp8; // IMP=0x3029a56c
- (BOOL)setActiveCategoryVolumeTo:(float)fp8;   // IMP=0x3029a254
- (BOOL)setActiveCategoryVolumeTo:(float)fp8 fallbackCategory:(id)fp12 resultVolume:(float *)fp16 affectedCategory:(id *)fp20;  // IMP=0x3029a1e0
- (BOOL)setActiveCategoryVolumeTo:(float)fp8 forRoute:(id)fp12 andDeviceIdentifier:(id)fp16;    // IMP=0x3029a36c
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;  // IMP=0x3029a850
- (BOOL)toggleActiveCategoryMuted;      // IMP=0x3029a438
- (BOOL)toggleActiveCategoryMutedForRoute:(id)fp8 andDeviceIdentifier:(id)fp12; // IMP=0x3029a478

@end