/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

typedef struct {
    int _field1;
    int _field2;
    id _field3;
    id _field4;
    float _field5;
    int _field6;
    SEL _field7;
    id _field8;
} CDAnonymousStruct2;

typedef struct {
    double width;
    double height;
} CDAnonymousStruct1;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
} CDAnonymousStruct9;

typedef struct {
    id _field1;
    id _field2;
    id _field3;
    id _field4;
} CDAnonymousStruct13;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
} CDAnonymousStruct14;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
} CDAnonymousStruct3;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    char _field5;
    char _field6;
} CDAnonymousStruct4;

typedef struct {
    float _field1;
    float _field2;
} CDAnonymousStruct5;

typedef struct {
    struct CGRect left;
    struct CGRect middle;
    struct CGRect right;
} CDAnonymousStruct8;

typedef struct {
    CDAnonymousStruct8 top;
    struct {
        struct CGRect _field1;
        struct CGRect _field2;
        struct CGRect _field3;
    } middle;
    struct {
        struct CGRect _field1;
        struct CGRect _field2;
        struct CGRect _field3;
    } bottom;
} CDAnonymousStruct10;

typedef struct {
    unsigned char pathIndex;
    unsigned char pathIdentity;
    unsigned char pathProximity;
    float pathPressure;
    float pathMajorRadius;
    struct CGPoint pathLocation;
    struct __GSWindow *pathWindow;
} CDAnonymousStruct11;

typedef struct {
    int count;
    int ids[10];
} CDAnonymousStruct6;

typedef struct {
    struct CGRect _field1;
    struct CGRect _field2;
    struct CGRect _field3;
    struct CGRect _field4;
    struct CGRect _field5;
    id _field6;
    id _field7;
    unsigned int _field8;
    unsigned int _field9;
    unsigned int _field10;
    id _field11;
} CDAnonymousStruct7;

typedef struct {
    char _field1;
    union {
        struct {
            id _field1;
            id _field2;
        } _field1;
        struct __GSEvent *_field2;
    } _field2;
} CDAnonymousStruct12;

typedef struct {
    int _field1;
    unsigned short _field2;
    unsigned short _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    unsigned char _field10;
    unsigned char _field11;
    CDAnonymousStruct11 _field12[0];
} CDAnonymousStruct15;


typedef union {
    UIImage *image;
    UIView *view;
} CDAnonymousUnion1;

/*
 * File: ../Frameworks/UIKit.framework/UIKit
 * Arch: PowerPC 7400 (ppc7400)
 *       Current version: 747.19.0, Compatibility version: 1.0.0
 */